NejatOfficial/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

from Post import views


urlpatterns = [
    url('admin/', admin.site.urls),

    url(r'^$', home_view, name='home'),
    url(r'^Post/', include('Post.urls')),
    url (r'^accounts/', include ('accounts.urls')),
    url (r'^about/', views.about, name= 'about'),
    url (r'^contact/', views.contact, name= 'contact'),


]

urlpatterns +=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)  #upload edilecek dosyaların url adresleri tanımlandı.

Post/urls.py
from .views import *
from django.conf.urls import url



app_name = 'post'

urlpatterns = [

    url(r'^index/$', post_index, name="index"),

    url(r'^create/$', post_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/update$', post_update, name= "update"),
    url(r'^(?P<slug>[\w-]+)/delete$', post_delete, name= "delete"),
]

accounts/urls.py
from .views import *
from django.conf.urls import url



app_name = 'accounts'

urlpatterns = [

    url(r'^login/$', login_view, name="login"),
    url(r'^register/$', register_view, name="register"),
    url (r'^logout/$', logout_view, name="logout"),

]

Home/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length= 100, verbose_name="İsim Soyisim")
    email = models.EmailField()
    message = models.TextField(max_length= 3000, verbose_name= "Mesajınız")
    sending_date = models.DateTimeField(auto_now_add=True, verbose_name="Gönderim Tarihi")

contact/forms.py
from django import forms

from contact.models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [
            "name",
            "email",
            "message",
        ]

Home/views.py
from django.shortcuts import render,HttpResponse

# Create your views here.

def home_view(request): #view olması için en az 1 tane argüman almalı
    return render(request, 'home.html', {}) #ilk argüman olmalı, ikincisi html çıktısı, {} => anahtar

# Create your views here.

contact/views.py
from django.shortcuts import render
from .forms import ContactForm

def sendMessage(request):
    form = ContactForm()
    return render(request, "contact.html", {"form":form},)
# Create your views here.

templates/aboutme.html
{% extends 'base.html' %}

{%block title%}Anasayfa - {{block.super}}{%endblock%}
{% block body %}
{% load static %}

 <div class="container">

      <!-- Introduction Row -->
      <h1 class="my-4">Hakkımda
        <small>Sizinle Tanışmak Güzel</small>
      </h1>

      <!-- Team Members Row -->

        <div class="col-lg-12 col-sm-12 text-center mb-12">
          <img class="rounded-circle img-fluid d-block mx-auto" src="{% static 'aboutme/image/ÖFOkuyucu.jpg'%}" alt="">
          <h3>Ömer Faruk OKUYUCU
            <small>Yazar</small>
          </h3>
          <p>İlk ve orta öğrenimini Tunceli ve İskenderun'da, lise eğitimini İskenderun Lisesi'nde, lisans eğitimini İstanbul Üniversitesi Fen Fakültesi Fizik bölümünde tamamladı.

      Eğitim sektörünün farklı alanlarında öğretmen, zümre başkanı, yazar, editör, rehberlik uzmanı, idareci ve yönetici olarak 13 yıl çalıştı. Yöneticilik, Liderlik, Girişimcilik, Pazarlama, İletişim Becerileri, Zaman Yönetimi, Kişisel Gelişim, Temel Psikoloji, İş Sağlığı ve Güvenliği, Eğitimcilik, İlk Yardım üzerine çeşitli eğitimler almıştır.
      Üniversite Hazırlık Rehberliği ile ilgili birçok seminer ve eğitim vermiştir. Yayınlanmış birçok fizik dersi, eğitim ve güncel olaylar üzerine kitap, dergi, test ve yayını bulunmaktadır. Sektörel doyuma ulaştığını düşündüğü için, 2013 yılında Üsküdar Üniversitesi'nde öğretim görevlisi olarak çalışmaya başladı.
      Üsküdar Üniversitesi Sağlık Bilimleri Enstitüsü İş Sağlığı ve Güvenliği Programı'nda yüksek lisans programını bitirmiştir.
</p>
        </div>

 </div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale =1">
    <title>{%block title%}Nejat Official{%endblock%} </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'header.html' %}
    {% include 'messages.html' %}
    {% block body %}

    {% endblock %}

    <!--<script src = "{% static 'js/jquery.min.js'%}"> </script> -->
    <script src = "{% static 'js/bootstrap.min.js'%}"> </script>

</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{%block title%}Anasayfa - {{block.super}}{%endblock%}
{% block body %}

<hr>
<div class = "container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <form method="POST" enctype="multipart/form-data">  <!-- Arama çubuğunda çıkmasını engelledi -->
                    {% csrf_token %}
                    <h1>İletişim Formu</h1>
                    <br>
                    {{form|crispy}} <!-- form nesnesini aktardık -->

                    <input class="btn btn-primary" type="submit" value="Gönder">


                 </form>
            </div>
        </div>
    </div>

{%endblock%}

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="/static/img/Nejat_T.png">
            </a>
            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand"></a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Site içinde ara" value="{{request.GET.q}}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'post:create' %}">Yazı Ekle</a></li>
                {%endif%}
                <li><a href="{% url 'home' %}">Anasayfa</a></li>
                <li><a href="{% url 'post:index' %}">Blog</a></li>
                <li><a href="{% url 'about' %}">Hakkımda</a></li>
                <li><a href="{% url 'contact' %}">İletişim</a></li>
                {%if not request.user.is_authenticated%}
                    <!--<li><a href="{% url 'accounts:register'%}"> Üye Ol</a> </li> üye kaydı-->
                    <li><a href="{% url 'accounts:login'%} "> Giriş</a> </li>
                {%else%}
                    <li><a href="{% url 'accounts:logout'%} "> Çıkış Yap</a> </li>
                {%endif%}
            </ul>

        </nav>

    </div>
</nav>

templates/messages.html
 {% if messages %}

     {% for message in messages %}
         <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
        </div>

     {% endfor %}

 {% endif %}